In [1]:
import numpy as np

### ndarray的基本属性

In [2]:
a = np.array([1,3,5,7,9])
a

array([1, 3, 5, 7, 9])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.size

5

In [5]:
a.ndim

1

In [6]:
a.shape

(5,)

In [7]:
A = np.array(
    [
        [1,3,5,7,9],
        [2,4,6,8,0]
    ]
)

In [8]:
A.shape

(2, 5)

In [9]:
A.dtype

dtype('int32')

In [10]:
A.itemsize

4

## 数组的基本创建方法

In [11]:
a = np.array([1,3,5,7,9])
a

array([1, 3, 5, 7, 9])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [14]:
np.arange(1,6,2) #最后的2代表步长

array([1, 3, 5])

In [15]:
np.ones(2)

array([1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.eye(3) #创建n*n的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.linspace(1,10,num=5,endpoint=False) #endpoint改为False，则结尾数据不包括

array([1. , 2.8, 4.6, 6.4, 8.2])

In [23]:
np.linspace(1,10,num=6)[:5]

array([1. , 2.8, 4.6, 6.4, 8.2])

In [24]:
[1,2,3,4,5]*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [31]:
a=np.linspace(1,10,4)
b=np.linspace(1,10,4,endpoint=False)
c=np.concatenate((a,b))
c

array([ 1.  ,  4.  ,  7.  , 10.  ,  1.  ,  3.25,  5.5 ,  7.75])

### 列表中[1,2,3,4,5]每个元素乘以2

In [25]:
[1,2,3,4,5]*2 #这是错误做法

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [26]:
b = np.array([1,2,3,4,5])
b * 2

array([ 2,  4,  6,  8, 10])

### 随机数生成

In [34]:
np.random.randint(1,100,size=(3,5))

array([[83, 19, 48, 57,  3],
       [81, 49, 46, 59, 36],
       [10, 37, 67, 16, 14]])

In [40]:
np.random.seed(666) #随机种子一旦确定则与他一起执行的生成随机数代码生成的随机数不会改变
np.random.randint(1,32,size=6)

array([13,  3, 14, 31, 31,  7])

In [41]:
np.random.random(size=(2,3))

array([[0.72785806, 0.95145796, 0.0127032 ],
       [0.4135877 , 0.04881279, 0.09992856]])

In [42]:
np.random.normal(2.5,3.8,size=(5,3))  #指定数组形状，每个元素取值都是从指定正态分布中获取的

array([[-2.93237441,  2.6461846 , -0.42952457],
       [ 4.82900362, -1.54575027,  6.42977833],
       [-0.85130266,  7.26242748,  2.60646355],
       [ 4.05251734,  4.54928546, -3.38941863],
       [ 5.27196517,  1.25757189,  6.83707973]])

### 聚合运算

In [44]:
x = np.array([3,5,7,9])
x

array([3, 5, 7, 9])

In [45]:
np.max(x)

9

In [46]:
x.max()

9

In [47]:
np.min(x)

3

In [48]:
M = np.random.randint(1,100,size=(3,4))
M

array([[87, 28, 80, 39],
       [28, 81, 58, 84],
       [39, 10, 52, 78]])

In [49]:
M.max()

87

In [50]:
M.max(axis=0)

array([87, 81, 80, 84])

In [51]:
M.max(axis=1)

array([87, 84, 78])

In [52]:
np.var(M)

642.2222222222222

In [53]:
np.std(M)

25.342103744997615

In [54]:
np.std(M) ** 2

642.2222222222222

In [55]:
np.var(M,axis=0)

array([656.22222222, 908.22222222, 144.88888889, 398.        ])

In [56]:
np.var(M,axis=1)

array([646.25  , 503.6875, 599.6875])

### 数组形状变换

In [58]:
a = np.arange(1,40)

In [59]:
a.reshape((3,-1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

### 二维数组切片的使用

In [60]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
a[1:,2:4]

array([[ 7,  8],
       [12, 13]])

### 数组的合并

In [64]:
X = np.random.randint(1,100,size=(5,3))
Y = np.random.randint(1,100,size=(3,3))

In [65]:
X

array([[45, 91, 80],
       [43, 21, 34],
       [40, 38, 94],
       [13, 83,  3],
       [99, 71, 29]])

In [66]:
Y

array([[70, 73,  6],
       [11, 85,  9],
       [44, 75,  5]])

In [67]:
np.concatenate((X,Y),axis=0)

array([[45, 91, 80],
       [43, 21, 34],
       [40, 38, 94],
       [13, 83,  3],
       [99, 71, 29],
       [70, 73,  6],
       [11, 85,  9],
       [44, 75,  5]])

In [69]:
np.vstack((X,Y))

array([[45, 91, 80],
       [43, 21, 34],
       [40, 38, 94],
       [13, 83,  3],
       [99, 71, 29],
       [70, 73,  6],
       [11, 85,  9],
       [44, 75,  5]])

In [70]:
X

array([[45, 91, 80],
       [43, 21, 34],
       [40, 38, 94],
       [13, 83,  3],
       [99, 71, 29]])

In [71]:
X.T

array([[45, 43, 40, 13, 99],
       [91, 21, 38, 83, 71],
       [80, 34, 94,  3, 29]])

In [72]:
np.concatenate((X.T,Y),axis=1)

array([[45, 43, 40, 13, 99, 70, 73,  6],
       [91, 21, 38, 83, 71, 11, 85,  9],
       [80, 34, 94,  3, 29, 44, 75,  5]])

In [73]:
np.hstack((X.T,Y))

array([[45, 43, 40, 13, 99, 70, 73,  6],
       [91, 21, 38, 83, 71, 11, 85,  9],
       [80, 34, 94,  3, 29, 44, 75,  5]])

In [74]:
X

array([[45, 91, 80],
       [43, 21, 34],
       [40, 38, 94],
       [13, 83,  3],
       [99, 71, 29]])

In [78]:
np.split(X,[1,3],axis=0)

[array([[45, 91, 80]]),
 array([[43, 21, 34],
        [40, 38, 94]]),
 array([[13, 83,  3],
        [99, 71, 29]])]